apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-eureka-server-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-eureka-server-sample
  template:
    metadata:
      labels:
        app: spring-eureka-server-sample
    spec:
      containers:
        - name: springboot
          image: 192.168.0.105:8081/local-docker/ankitwaa:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
      imagePullSecrets:
        - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: spring-eureka-server-sample
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spring-eureka-server-sample