apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-eureka-server-sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-eureka-server-sample
  template:
    metadata:
      labels:
        app: spring-eureka-server-sample
    spec:
      containers:
        - name: springboot
          image: local-docker/ankitwaa
          ports:
            - containerPort: 8761
          env:
            - name: PORT
              value: "8761"
---
apiVersion: v1
kind: Service
metadata:
  name: jhooq-springboot
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761Dockerfile
  selector:
    app: spring-eureka-server-sample